### PR TITLE
Add functionality to save graph into file

### PR DESCRIPTION
**Pull request by jonas-chow**
Saves the graph as a .png if the -f flag is provided.

### CODE REVIEW

**Comment by nbvannhi** [comment]
There would be lots of conflicts when merging because I was also editing `ShowCommand` with `show -g` feature so it clashed a lot with your work.. Hence I would suggest merging my branch `v1.3-show-group` into `master` first. Then I could resolve the conflicts for your branch to merge (because I have been doing the `ShowCommand` anw)

So @leonghongfai please take note and not merge it for now

**Comment by jonas-chow** [comment]
@nbvannhi thanks for volunteering to help with the merge conflicts. I'll just list a few important pointers wrt how I implemented this so it's easier to resolve.

1. The actual saving mechanism is implemented in `MainWindow.java`, shouldn't need to touch it though, I think it should be free of conflicts.
2. The `Path` is parsed from the `PREFIX_FILE` inside the `ShowCommandParser`. 
    1. If `PREFIX_FILE` isn't specified, `Path` will be `null`, which is returned in the `CommandResult` as a way to tell the system to not save. 
    2. If `PREFIX_FILE` is specified, `Path` will be passed to `MainWindow` through the `CommandResult`
3. You need to ensure that your constructor for parsing with `Group` also takes in a `Path`
4. Also, I added a check in `ShowCommandParser` to throw a `ParseException` if there is no preamble, and no prefixes.

**Comment by nbvannhi** [comment]
@leonghongfai it's ready for review now!

**Review by leonghongfai — CHANGES_REQUESTED** [review]
I cannot seem to find where the issue takes place but for other commands, upon enterring only the command word eg "delete", the error message with the correct format & example shows up. But for show, plainly typing "show" does not change whatever is currently written in the resultDisplay. To get the invalid command error for show,  I have to type "show x" where x is a non-numeric character.

**Comment by nbvannhi** [comment]
> I cannot seem to find where the issue takes place but for other commands, upon enterring only the command word eg "delete", the error message with the correct format & example shows up. But for show, plainly typing "show" does not change whatever is currently written in the resultDisplay. To get the invalid command error for show, I have to type "show x" where x is a non-numeric character.

That's strange since it works fine on my computer

image

**Review by leonghongfai — APPROVED** [review]
LGTM

**Pull request merged**
